# Generated by Django 5.0.6 on 2024-05-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
