# Generated by Django 5.0.6 on 2024-05-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='format',
            field=models.CharField(max_length=4),
        ),
    ]
