
# name of our workflow
name: Django CI/CD Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🛸
# triggers for our workflow
on:
  # opening a pull request to master and develop branch will be a trigger
  pull_request:
    branches:
      - develop
      - master
  # any code pushed to master and develop branch will also be a trigger
  push:
    branches:
      - master
      - develop


# three job definition
jobs:
  run_unittests: # health check job for testing and code formatting check
    runs-on: ubuntu-latest # os for running the job
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - name: Checkout repository code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} # caching dependency will make our build faster.
        uses: actions/setup-python@v4 # for more info checkout pip section documentation at https://github.com/actions/cache
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependacies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests # running tests
        run: |
          echo "SECRET_KEY = 'django-insecure-dummy-secret'" >  ./.env
          echo "SECRET_KEY = 'django-insecure-dqewrkg^-wzjm8bbt2q2$(cwy0ikn%+b$0a%-2l62e07lw5z#d'" > ./.env
          echo "EMAIL_HOST_USER = "akromjonrustamov56@gmail.com" > ./.env
          echo "EMAIL_HOST_PASSWORD = 'qhdcsnmozcnrngih'" > ./.env
          python manage.py test
